### ISSUE TITLE
Crash on latest vscode 1.93.1

### ISSUE THREAD

**Issue by 4fort** [HealKnix/macos-titlebar-for-windows#5]
```
[error] Error: Titlebar overlay is not enabled
    at CodeWindow.updateWindowControls (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:117:120297)
    at CodeWindow.n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:117:117930)
    at new C (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:117:123288)
    at new CodeWindow (/usr/share/code/resources/app/out/vs/modules/patch.main.js:70:11)
    at $.o (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:64:1608)
    at $.createInstance (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:64:1100)
    at j.rb (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:118:46308)
    at j.cb (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:118:34790)
    at j.Z (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:118:33699)
    at j.open (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:118:29689)
    at async yt.startup (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:118:58105)
    at async Fe.a (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:120:1275)
```

this is the main.log

**Comment by HealKnix** [comment]
After the new VS Code update the developers may have messed with electron. That's why `Apc Customize UI++` extension is broken. So we are waiting for this extension to be updated. If it is updated...

**Comment by 4fort** [comment]
> After the new VS Code update the developers may have messed with electron. That's why `Apc Customize UI++` extension is broken. So we are waiting for this extension to be updated. If it is updated...

so apparently this extension left an apc stylesheet to settings.json and surprisingly still works with this extension disabled. 

Also I’m on linux and disabling the experimental window controls button to match with native on custom might be the reason why it worked.

I don’t know if I should close this issue or not since what worked to me isn’t due to fixing the extension.

**Comment by HealKnix** [comment]
Hmm... That's interesting)))
So even with APC turned off, you still see the custom titlebar?
Maybe it's just a quirk of the operating system.
I’m on Win 11, and I can't afford to do that.

**Comment by 4fort** [comment]
> Hmm... That's interesting))) So even with APC turned off, you still see the custom titlebar? Maybe it's just a quirk of the operating system. I’m on Win 11, and I can't afford to do that.

I don't think you can apply custom css to vscode without APC.

I think you're trying to say is APC not working on your latest vscode which it didn't to me aswell on previous version after 1.91; Try updating to 1.93.

**Comment by HealKnix** [comment]
We seem to have misunderstood each other a bit. I have the latest version of VS Code 1.93.1 installed. The styles related to the titlebar stopped working about three weeks ago, when the 1.93 update was released. People have already written to me about this issue, and I also noticed that the styles for the titlebar stopped working. Then I dug up some information in the `Apc Customize UI++` repository, and other people also had issues after this update. As of now, APC still hasn't been updated. That's the situation :p

**Comment by HealKnix** [comment]
The tricky part is that the custom titlebar only works when
```json
"apc.electron": {
        "titleBarStyle": "hiddenInset" 
}
```
is enabled.
But on Windows, this causes VS Code to crash at startup.

**Comment by HealKnix** [comment]
I can't say anything about other operating systems since I don't have access to them.

**Comment by HealKnix** [comment]
And yeah, about the custom css. I wasn't saying it would work without Apc))) I understand that without Apc the styles won't work, which is why I was surprised that everything stayed the same for you, even with Apc turned off. 0_o

**Comment by 4fort** [comment]
> The tricky part is that the custom titlebar only works when
> 
> ```json
> "apc.electron": {
>         "titleBarStyle": "hiddenInset" 
> }
> ```
> 
> is enabled. But on Windows, this causes VS Code to crash at startup.

Correct! About that as well, I commented that line out and my vscode works with APC enabled and without crashing. I believe that is what lead to vscode crashing with APC. saw it [here](https://github.com/microsoft/vscode/issues/226860#issuecomment-2341555551)

**Comment by HealKnix** [comment]
Oh, forget what I said. I misunderstood you.
I thought you had titlebar styles working, but you just meant css styles that are not related to the titlebar xD

**Comment by HealKnix** [comment]
I was reading between the lines, so I apologize for my misunderstanding.

**Comment by HealKnix** [comment]
And so yes, the problem still remains. I hope that the creator of Apc will fix it, otherwise I will have to deprecate the extension

**Comment by 4fort** [comment]
> Oh, forget what I said. I misunderstood you. I thought you had titlebar styles working, but you just meant css styles that are not related to the titlebar xD

Lol, actually it is the titlebar
![image](https://github.com/user-attachments/assets/936b2d96-3482-4e09-92d8-be3bd5cbda7a)


> I was reading between the lines, so I apologize for my misunderstanding.

You're good 😂

**Comment by HealKnix** [comment]
So... I'm definitely broken now)))))
For clarification, has it always been there or has it recently appeared?
I can't get the gist of it xD

**Comment by HealKnix** [comment]
God, it's been a long time since I've seen that traffic light...

**Comment by jyuangrace** [comment]
Hello HealKnix, I'm stilling using your vscode extension macos titlebar. However, I'm thinking of updating vscodium to latest build. I would hate to miss the titlebar. Do you know of any alternative I could use at this time? thank you.

**Comment by HealKnix** [comment]
> Hello HealKnix, I'm stilling using your vscode extension macos titlebar. However, I'm thinking of updating vscodium to latest build. I would hate to miss the titlebar. Do you know of any alternative I could use at this time? thank you.

Thank you for using my extension!
Unfortunately, there are no alternatives. That's why I made this extension for lack of alternatives)))
I'm on version 1.92.1 myself, because redefining titlebar styles works on it. I would like to upgrade to a more recent version myself, but I'm already so used to this titlebar that I'm willing to sacrifice the new functionality of the new versions :D
